# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PYOjT5gWieL17WpSy50z4NjZLOe_VJE7
"""

!pip install transformers torch gradio PyPDF2 -q